### ISSUE TITLE
/usr/lib/libcudart.so.10.1: version `libcudart.so.10.1' not found

### ISSUE THREAD

**Issue by xhuan8** [daniilidis-group/neural_renderer#107]
hi,

i have pytorch 1.4 with cuda 10.0 installed, but when try neural renderer, it shows this error:

Traceback (most recent call last):
  File "./examples/example1.py", line 12, in <module>
    import neural_renderer as nr
  File "/home/xiehuan/anaconda3/lib/python3.8/site-packages/neural_renderer/__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "/home/xiehuan/anaconda3/lib/python3.8/site-packages/neural_renderer/load_obj.py", line 8, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /usr/lib/libcudart.so.10.1: version `libcudart.so.10.1' not found (required by /home/xiehuan/anaconda3/lib/python3.8/site-packages/neural_renderer/cuda/load_textures.cpython-38-x86_64-linux-gnu.so)

the file 'libcudart.so.10.1' link to '/usr/local/cuda-10.0/lib64/libcublas.so.10.0.130'
is there any workaround to solve this problem?

**Comment by xhuan8** [comment]
fixed by run: pip3 install git+https://github.com/daniilidis-group/neural_renderer/

**Comment by dogecoin-developer** [comment]
Which branch did you use?

**Comment by xhuan8** [comment]
> Which branch did you use?

installed by "pip install neural_renderer_pytorch"
